#!/usr/bin/env bash
# Copyright © 2023 Kevin T. O'Donnell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include commands
@include exec
@include k8s
@include log
@include options

options::standard
options::set_description "Copies the keys from the validators to a directory \
  on the local host."
options::add -o l -d "label to select the validators" -a -m -e LABEL
options::add -o n -d "namespace to query (default: current context)" -a -e NAMESPACE
options::parse "$@"

log::info "Copying keys from pods with label $LABEL"
for pod in $(k8s::pod_names_for_label "$LABEL" "${NAMESPACE:-}" | sort); do
  node_name=$(k8s::ctl get pod "$pod" -o json | $(commands::use jq) -r '.spec.nodeName')
  log::info "Working on $node_name with pod $pod"
  mkdir -p "keys/$node_name"
  ln -s "$node_name" "keys/$pod"
  exec::capture k8s::ctl cp "$pod:/etc/sawtooth/keys/validator.priv" \
    "keys/$node_name/validator.priv" -c validator
  exec::capture k8s::ctl cp "$pod:/etc/sawtooth/keys/validator.pub" \
    "keys/$node_name/validator.pub" -c validator
done
