#!/usr/bin/env bash
# Copyright © 2023 Kevin T. O'Donnell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include commands
@include k8s
@include log
@include options

options::standard
options::description "Fetch the logs for the containers into local files"
options::add -o l -d "label of pod selector" -a -m -e selector
options::add -o c -d "container whose logs to dump (defaults to all)" -a -e container
options::add -o n -d "namespace (defaults to current-context namespace)" -a -e namespace
options::parse "$@"
shift $((OPTIND - 1))

# shellcheck disable=SC2154 # namespace exported by options::add -e
ns_args=()
if [ -n "$namespace" ]; then
  ns_args=(-n "$namespace")
fi
# shellcheck disable=SC2154 # selector/container exported by options::add -e
get_pods_cmd=(k8s::ctl get pods "${ns_args[@]}" -l "$selector" -o json)
# shellcheck disable=SC2154 # selector/container/namespace exported by options::add -e
log::info "Fetching logs of pods for selector $selector container: ${container:-all}${namespace:+ namespace: $namespace}"
for pod in $("${get_pods_cmd[@]}" |
  $(commands::use jq) -r '.items[].metadata.name'); do
  log_cmd=(k8s::ctl logs "${ns_args[@]}" "$pod" "--tail=10000" --timestamps)
  suffix=${container:-all}
  if [ -n "$container" ]; then
    log::info "Fetching $container logs of pod $pod to $pod.$suffix.out"
    log_cmd+=(-c "$container")
  else
    log::info "Fetching all logs of pod $pod to $pod.$suffix.out"
    log_cmd+=(--all-containers "--max-log-requests=100")
  fi
  "${log_cmd[@]}" | sed 's/\x1b\[[0-9;]*m//g' >"$pod.$suffix.out"
done
