#!/usr/bin/env bash
# Copyright © 2023 Kevin T. O'Donnell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include options

options::description "This will pack the target script producing a new script\
 with no @include statements"
options::standard
options::add -o f -d "the script to pack" -a -m -e TargetFile
options::add -o o -d "output file" -a -m -e OutputFile
options::parse "$@"
shift "$((OPTIND - 1))"

function ::get_includes() {
  local file=${1:?}
  grep "^@include" "$file" | awk '{print $NF}'
}

function get_all_includes() {
  local target=${1:?}
  local -a order=()
  declare -A seen=()

  log::info "Scanning script ${target}"
  for inc in $(::get_includes "${target}"); do
    if [ -z "${seen[$inc]:-}" ]; then
      log::info "Adding $inc"
      seen[$inc]="1"
      order+=("$inc")
    fi
  done
  local i=0
  while [ "$i" -lt "${#order[@]}" ]; do
    local current="${order[$i]}"
    for subinc in $(::get_includes "$(includer::find "$current")"); do
      if [ -z "${seen[$subinc]:-}" ]; then
        log::info "Adding $subinc"
        seen[$subinc]="1"
        order+=("$subinc")
      fi
    done
    i=$((i + 1))
  done
  for inc in "${order[@]}"; do
    echo "$inc"
  done
}

set -e
echo "#!/usr/bin/env bash" >"${OutputFile:?}"
grep -v "^@include" "$(includer::find doc)" |
  grep -v "includer.sh" |
  grep -v "^#!" >>"${OutputFile:?}"
grep -v "^@include" "$(includer::find annotations)" |
  grep -v "includer.sh" |
  grep -v "^#!" >>"${OutputFile:?}"

for inc in $(get_all_includes "${TargetFile:?}"); do
  if [ "$inc" = "annotations" ]; then
    continue
  elif [ "$inc" = "doc" ]; then
    continue
  fi
  grep -v "^@include" "$(includer::find "$inc")" |
    grep -v "includer.sh" |
    grep -v "^#!" >>"${OutputFile:?}"
done

grep -v "^@include" "${TargetFile}" |
  sed -E -e 's/BASH_SOURCE\[-?[0-9]+\]/BASH_SOURCE[0]/g' |
  grep -v "includer.sh" |
  grep -v "^#!" >>"${OutputFile:?}"

echo >>"${OutputFile:?}"
