#!/usr/bin/env bash
# Copyright © 2023 Kevin T. O'Donnell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include commands
@include k8s
@include log
@include options

options::standard
options::description "Opens a tmux session with panels for each of the pods\
 and containers specified running the provided command."
options::add -o l -d "label to select for the console" -a -m -e LABEL
options::add -o c -d "command to execute in the console" -a -m -e COMMAND
options::add -o n -d "namespace to query (default: current context)" -a -e NAMESPACE
options::parse "$@"
shift $((OPTIND - 1))

SESSION=$LABEL

function tmux::cmd {
  $(commands::use tmux) "$@"
}

if tmux::cmd has-session -t "$SESSION"; then
  log::debug "Switch to session $SESSION"
  tmux::cmd switch-client -t "$SESSION"
else
  log::debug "Create session $SESSION"
  tmux::cmd new-session -s "$SESSION" -d
fi
WINDOW=$LABEL-$RANDOM
log::debug "Create and select window $WINDOW"
tmux::cmd new-window -n "$WINDOW"
tmux::cmd select-window -t "$WINDOW"
count=0
for pod in $(k8s::pod_names_for_label "$LABEL" "${NAMESPACE:-}" | sort); do
  if [ "$count" -gt 0 ]; then
    log::debug "Split window on session $SESSION"
    tmux::cmd split-window -v -t "$SESSION"
  fi
  log::debug "Execute on $SESSION: $(commands::use kubectl) $COMMAND pod/$pod $*"
  tmux::cmd send-keys -t "$SESSION" "$(commands::use kubectl) $COMMAND pod/$pod $*" C-m
  log::debug "Tile window $WINDOW"
  tmux::cmd select-layout tiled
  count=$((count + 1))
done
