#!/usr/bin/env bash
# Copyright © 2023 Kevin T. O'Donnell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include k8s
@include options

options::standard
options::description "prints out the resource name followed by its labels, one\
 per line."
options::add -o t -d "resource type to examine" -a -m -e RESOURCE_TYPE
options::parse "$@"
shift $((OPTIND - 1))

for line in $(k8s::ctl get "$RESOURCE_TYPE" --show-labels --no-headers "$@" | awk '{print $1":"$NF}'); do
  resource_name=$(echo "$line" | awk -F: '{print $1}')
  labels=$(echo "$line" | awk -F: '{print $NF}')
  col1="$resource_name"
  for l in ${labels//,/ }; do
    printf "%-45.45s %-30s\n" "$col1" "$l"
  done
done
