#!/usr/bin/env bash
# Copyright © 2023 Kevin T. O'Donnell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include exec
@include git
@include log
@include options

options::standard
options::description "Switch all of the the branch of all of the target\
 repositories to the specified branch"
options::add -o c -d "client repository set" -a -e CLIENT
options::add -o o -d "target organization" -a -m -e ORG
options::add -o b -d "branch to switch to" -a -m -e BRANCH
options::add -o n -d "if this is a new branch" -x NEW_BRANCH
options::parse "$@"
shift $((OPTIND - 1))

if [ -n "$CLIENT" ]; then
  TARGET_DIR="${HOME}/git/clients/${CLIENT}/${ORG}"
else
  TARGET_DIR="${HOME}/git/${ORG}"
fi

log::info "Scanning $TARGET_DIR"
for d in "$TARGET_DIR"/*; do
  log::info "Switching $d"
  if [ -d "$d/.git" ]; then
    if ! cd "$d"; then
      log::warn "Cannot cd to $d"
      continue
    fi
    if [ "$NEW_BRANCH" = "true" ]; then
      if exec::capture git::cmd checkout -b "$BRANCH" "$@"; then
        log::info "Checked out into new branch $BRANCH in $d"
      else
        log::warn "Failed to create new branch $BRANCH in $d (see exec log); not falling back to checkout of an existing branch"
      fi
    elif exec::hide git::cmd checkout "$BRANCH" "$@"; then
      log::info "Checked out $BRANCH in $d"
    else
      log::warn "Failed to checkout branch $BRANCH in $d"
    fi
    if ! cd - >/dev/null; then
      log::warn "Cannot cd back to OWD"
      continue
    fi
  else
    continue
  fi
done
